use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-env-changed=OPT_LEVEL");
    println!("cargo:rerun-if-env-changed=TARGET");

    if let Ok(profile) = env::var("PROFILE") {
        println!("cargo:rustc-env=BUILD_PROFILE={profile}");
    }
    if let Ok(opt_level) = env::var("OPT_LEVEL") {
        println!("cargo:rustc-env=BUILD_OPT_LEVEL={opt_level}");
    }
    if let Ok(target) = env::var("TARGET") {
        println!("cargo:rustc-env=BUILD_TARGET={target}");
    }

    generate_env_pool_methods();
}

fn generate_env_pool_methods() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let src_dir = manifest_dir.join("src/lib_parts/env_pool");
    let fragments = [
        "20_constructors.rs",
        "30_settings.rs",
        "40_reset_step.rs",
        "50_logits.rs",
    ];

    for fragment in fragments {
        println!(
            "cargo:rerun-if-changed={}",
            src_dir.join(fragment).display()
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("env_pool_methods.rs");

    let mut out = String::new();
    out.push_str("// @generated by weiss_py/build.rs. Do not edit directly.\n");
    out.push_str("#[pymethods]\n");
    out.push_str("impl PyEnvPool {\n");
    for fragment in fragments {
        let content = fs::read_to_string(src_dir.join(fragment))
            .unwrap_or_else(|err| panic!("read {fragment} failed: {err}"));
        out.push_str(&content);
        if !content.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out.push_str("}\n");

    fs::write(&dest, out).unwrap_or_else(|err| panic!("write {dest:?} failed: {err}"));
}
