use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=PROFILE");
    println!("cargo:rerun-if-env-changed=OPT_LEVEL");
    println!("cargo:rerun-if-env-changed=TARGET");

    if let Ok(profile) = env::var("PROFILE") {
        println!("cargo:rustc-env=BUILD_PROFILE={profile}");
    }
    if let Ok(opt_level) = env::var("OPT_LEVEL") {
        println!("cargo:rustc-env=BUILD_OPT_LEVEL={opt_level}");
    }
    if let Ok(target) = env::var("TARGET") {
        println!("cargo:rustc-env=BUILD_TARGET={target}");
    }

    generate_env_pool_methods();
}

fn generate_env_pool_methods() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let src_dir = manifest_dir.join("src/lib_parts/env_pool");
    let fragments = [
        "20_constructors.rs",
        "30_status_config.rs",
        "31_reset_seeded.rs",
        "32_replay_debug.rs",
        "33_legal_sampling.rs",
        "34_properties.rs",
        "40_reset_all.rs",
        "41_reset_indices.rs",
        "42_reset_done.rs",
        "43_step_direct.rs",
        "44_step_first_legal.rs",
        "45_step_sample_legal.rs",
        "46_rollout_first_legal.rs",
        "46_rollout_heuristic_public.rs",
        "46_rollout_first_legal_nomask.rs",
        "46_rollout_sample_legal.rs",
        "47_debug_auto_reset.rs",
        "50_logits_select.rs",
        "51_logits_sample.rs",
        "52_logits_sample_logp.rs",
    ];

    for fragment in fragments {
        println!(
            "cargo:rerun-if-changed={}",
            src_dir.join(fragment).display()
        );
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("env_pool_methods.rs");

    let mut out = String::new();
    out.push_str("// @generated by weiss_py/build.rs. Do not edit directly.\n");
    out.push_str("#[pymethods]\n");
    out.push_str("impl PyEnvPool {\n");
    for fragment in fragments {
        let content = fs::read_to_string(src_dir.join(fragment))
            .unwrap_or_else(|err| panic!("read {fragment} failed: {err}"));
        out.push_str(&content);
        if !content.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out.push_str("}\n");

    fs::write(&dest, out).unwrap_or_else(|err| panic!("write {dest:?} failed: {err}"));
}
