from __future__ import annotations

from ._buffers import EnvPoolBuffers, EnvPoolTrajectoryBuffers, make_pool
from .weiss_sim import (
    ACTION_SPACE_SIZE,
    ACTOR_NONE,
    DECISION_KIND_NONE,
    POLICY_VERSION,
    OBS_LEN,
    PASS_ACTION_ID,
    SPEC_HASH,
    BatchOutMinimalI16,
    BatchOutMinimalI16LegalIds,
    BatchOutDebug,
    BatchOutMinimal,
    BatchOutMinimalNoMask,
    BatchOutTrajectory,
    BatchOutTrajectoryI16,
    BatchOutTrajectoryI16LegalIds,
    BatchOutTrajectoryNoMask,
    EnvPool,
    action_spec_json,
    build_info,
    decode_action_id,
    observation_spec_json,
    __version__,
)
from .rl import (
    RlStep,
    pass_action_id_for_decision_kind,
    reset_rl,
    step_rl,
    step_rl_sample_from_logits,
    step_rl_select_from_logits,
)
from .api import db_info, export_spec_bundle, fast, inspect, make
from .catalog import cards
from .config_types import CurriculumOverrides, DeckInput, EndConditionOverrides
from .league import (
    AgentSummary,
    ClockGreedSummary,
    FirstPlayerBiasSummary,
    MatchRecord,
    rank_agents,
    records_from_step,
    round_robin_schedule,
    sample_population_schedule,
    summarize_clock_greed_from_replay,
    summarize_first_player_bias,
    summarize_records,
)
from .errors import (
    CardLookupError,
    ConfigConflictError,
    DbMismatchError,
    DeckSpecError,
    DeckValidationError,
    WeissSimError,
)
from .runner import WeissEnv
from .types import CardRef, LegalActions, ResetBatch, StepBatch


def spec_bundle() -> dict[str, object]:
    """Return the current observation/action spec bundle as a Python dict."""
    return export_spec_bundle()


__all__ = [
    "EnvPool",
    "EnvPoolBuffers",
    "EnvPoolTrajectoryBuffers",
    "BatchOutMinimal",
    "BatchOutMinimalI16",
    "BatchOutMinimalI16LegalIds",
    "BatchOutMinimalNoMask",
    "BatchOutTrajectory",
    "BatchOutTrajectoryI16",
    "BatchOutTrajectoryI16LegalIds",
    "BatchOutTrajectoryNoMask",
    "BatchOutDebug",
    "ACTION_SPACE_SIZE",
    "ACTOR_NONE",
    "DECISION_KIND_NONE",
    "POLICY_VERSION",
    "OBS_LEN",
    "SPEC_HASH",
    "RlStep",
    "reset_rl",
    "step_rl",
    "step_rl_select_from_logits",
    "step_rl_sample_from_logits",
    "pass_action_id_for_decision_kind",
    "PASS_ACTION_ID",
    "observation_spec_json",
    "action_spec_json",
    "decode_action_id",
    "build_info",
    "make_pool",
    "spec_bundle",
    "export_spec_bundle",
    "db_info",
    "make",
    "fast",
    "inspect",
    "cards",
    "WeissEnv",
    "CurriculumOverrides",
    "EndConditionOverrides",
    "DeckInput",
    "MatchRecord",
    "AgentSummary",
    "FirstPlayerBiasSummary",
    "ClockGreedSummary",
    "round_robin_schedule",
    "sample_population_schedule",
    "records_from_step",
    "summarize_records",
    "summarize_first_player_bias",
    "summarize_clock_greed_from_replay",
    "rank_agents",
    "CardRef",
    "LegalActions",
    "ResetBatch",
    "StepBatch",
    "WeissSimError",
    "DeckSpecError",
    "CardLookupError",
    "DeckValidationError",
    "ConfigConflictError",
    "DbMismatchError",
    "__version__",
]
